// <auto-generated />
using System;
using HOSPITAL_MANAGEMENT_SYSTEM__HMS_.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HOSPITAL_MANAGEMENT_SYSTEM__HMS_.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HOSPITAL_MANAGEMENT_SYSTEM__HMS_.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Scheduled");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2026, 9, 29, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            PatientId = 1,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2026, 9, 29, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            PatientId = 7,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2026, 9, 29, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            PatientId = 3,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            AppointmentDate = new DateTime(2026, 9, 29, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 7,
                            PatientId = 4,
                            Status = "Cancelled"
                        },
                        new
                        {
                            Id = 5,
                            AppointmentDate = new DateTime(2026, 9, 28, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            PatientId = 5,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 6,
                            AppointmentDate = new DateTime(2026, 9, 28, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            PatientId = 8,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 7,
                            AppointmentDate = new DateTime(2026, 9, 27, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 6,
                            PatientId = 9,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 8,
                            AppointmentDate = new DateTime(2026, 10, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 8,
                            PatientId = 10,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 9,
                            AppointmentDate = new DateTime(2026, 10, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            PatientId = 2,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 10,
                            AppointmentDate = new DateTime(2026, 10, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            PatientId = 6,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 11,
                            AppointmentDate = new DateTime(2026, 9, 26, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            PatientId = 5,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 12,
                            AppointmentDate = new DateTime(2026, 9, 25, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 7,
                            PatientId = 1,
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("HOSPITAL_MANAGEMENT_SYSTEM__HMS_.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Cairo",
                            Name = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Giza",
                            Name = "Pediatrics"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Cairo",
                            Name = "Orthopedics"
                        },
                        new
                        {
                            Id = 4,
                            Location = "Giza",
                            Name = "Dermatology"
                        });
                });

            modelBuilder.Entity("HOSPITAL_MANAGEMENT_SYSTEM__HMS_.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "ahmed.hassan@hms.com",
                            FullName = "Ahmed Hassan",
                            Phone = "01010000001",
                            Salary = 45000m,
                            Specialization = "Cardiologist"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Email = "mona.adel@hms.com",
                            FullName = "Mona Adel",
                            Phone = "01010000002",
                            Salary = 42000m,
                            Specialization = "Cardiologist"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            Email = "omar.khaled@hms.com",
                            FullName = "Omar Khaled",
                            Phone = "01010000003",
                            Salary = 38000m,
                            Specialization = "Pediatrician"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            Email = "nour.samir@hms.com",
                            FullName = "Nour Samir",
                            Phone = "01010000004",
                            Salary = 36000m,
                            Specialization = "Pediatrician"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 3,
                            Email = "karim.tarek@hms.com",
                            FullName = "Karim Tarek",
                            Phone = "01010000005",
                            Salary = 50000m,
                            Specialization = "Orthopedic Surgeon"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 3,
                            Email = "salma.youssef@hms.com",
                            FullName = "Salma Youssef",
                            Phone = "01010000006",
                            Salary = 41000m,
                            Specialization = "Orthopedic Specialist"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 4,
                            Email = "youssef.emad@hms.com",
                            FullName = "Youssef Emad",
                            Phone = "01010000007",
                            Salary = 39000m,
                            Specialization = "Dermatologist"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 4,
                            Email = "laila.mostafa@hms.com",
                            FullName = "Laila Mostafa",
                            Phone = "01010000008",
                            Salary = 37000m,
                            Specialization = "Dermatologist"
                        });
                });

            modelBuilder.Entity("HOSPITAL_MANAGEMENT_SYSTEM__HMS_.Models.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Prescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("medicalRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 3,
                            Diagnosis = "Hypertension",
                            Notes = "Follow-up after two weeks.",
                            Prescription = "Amlodipine 5mg once daily"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 5,
                            Diagnosis = "Acute respiratory infection",
                            Notes = "Patient advised to return if symptoms worsen.",
                            Prescription = "Rest and fluids"
                        },
                        new
                        {
                            Id = 3,
                            AppointmentId = 7,
                            Diagnosis = "Knee ligament injury",
                            Notes = "MRI recommended.",
                            Prescription = "Physiotherapy and rest"
                        },
                        new
                        {
                            Id = 4,
                            AppointmentId = 11,
                            Diagnosis = "Mild eczema",
                            Notes = "Avoid known skin irritants.",
                            Prescription = "Topical moisturizer twice daily"
                        },
                        new
                        {
                            Id = 5,
                            AppointmentId = 12,
                            Diagnosis = "Migraine",
                            Notes = "Maintain regular sleep schedule.",
                            Prescription = "Paracetamol as needed"
                        },
                        new
                        {
                            Id = 6,
                            AppointmentId = 6,
                            Diagnosis = "Seasonal allergy",
                            Notes = "Review if symptoms persist.",
                            Prescription = "Antihistamine once daily"
                        });
                });

            modelBuilder.Entity("HOSPITAL_MANAGEMENT_SYSTEM__HMS_.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("BirthOfDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("patients", t =>
                        {
                            t.HasCheckConstraint("CK_Appointment_DateInPaste", "[BirthOfDate] < GETUTCDATE()");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Nasr City, Cairo",
                            BirthOfDate = new DateTime(1995, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Omar Ali",
                            Gender = "Male",
                            PhoneNumber = "01120000001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Dokki, Giza",
                            BirthOfDate = new DateTime(1998, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Sara Ahmed",
                            Gender = "Female",
                            PhoneNumber = "01120000002"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Heliopolis, Cairo",
                            BirthOfDate = new DateTime(1987, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Mahmoud Samir",
                            Gender = "Male",
                            PhoneNumber = "01120000003"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Giza",
                            BirthOfDate = new DateTime(2002, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Mariam Adel",
                            Gender = "Female",
                            PhoneNumber = "01120000004"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Maadi, Cairo",
                            BirthOfDate = new DateTime(1979, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Yassin Mohamed",
                            Gender = "Male",
                            PhoneNumber = "01120000005"
                        },
                        new
                        {
                            Id = 6,
                            Address = "October, Giza",
                            BirthOfDate = new DateTime(1991, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Hana Khaled",
                            Gender = "Female",
                            PhoneNumber = "01120000006"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Giza",
                            BirthOfDate = new DateTime(2014, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Adam Tarek",
                            Gender = "Male",
                            PhoneNumber = "01120000007"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Nasr City, Cairo",
                            BirthOfDate = new DateTime(2012, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Lina Hassan",
                            Gender = "Female",
                            PhoneNumber = "01120000008"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Shoubra, Cairo",
                            BirthOfDate = new DateTime(1983, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Mostafa Nabil",
                            Gender = "Male",
                            PhoneNumber = "01120000009"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Mohandessin, Giza",
                            BirthOfDate = new DateTime(2000, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Aya Emad",
                            Gender = "Female",
                            PhoneNumber = "01120000010"
                        });
                });

            modelBuilder.Entity("HOSPITAL_MANAGEMENT_SYSTEM__HMS_.Models.Appointment", b =>
                {
                    b.HasOne("HOSPITAL_MANAGEMENT_SYSTEM__HMS_.Models.Doctor", "Doctor")
                        .WithMany("appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HOSPITAL_MANAGEMENT_SYSTEM__HMS_.Models.Patient", "Patient")
                        .WithMany("appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HOSPITAL_MANAGEMENT_SYSTEM__HMS_.Models.Doctor", b =>
                {
                    b.HasOne("HOSPITAL_MANAGEMENT_SYSTEM__HMS_.Models.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HOSPITAL_MANAGEMENT_SYSTEM__HMS_.Models.MedicalRecord", b =>
                {
                    b.HasOne("HOSPITAL_MANAGEMENT_SYSTEM__HMS_.Models.Appointment", "Appointment")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("HOSPITAL_MANAGEMENT_SYSTEM__HMS_.Models.MedicalRecord", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("HOSPITAL_MANAGEMENT_SYSTEM__HMS_.Models.Appointment", b =>
                {
                    b.Navigation("MedicalRecord")
                        .IsRequired();
                });

            modelBuilder.Entity("HOSPITAL_MANAGEMENT_SYSTEM__HMS_.Models.Department", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("HOSPITAL_MANAGEMENT_SYSTEM__HMS_.Models.Doctor", b =>
                {
                    b.Navigation("appointments");
                });

            modelBuilder.Entity("HOSPITAL_MANAGEMENT_SYSTEM__HMS_.Models.Patient", b =>
                {
                    b.Navigation("appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
